version = 0.1
[default]

[default.build.parameters]
debug = true
use_container = false

[default.deploy]
[default.deploy.parameters]
stack_name = "dev-aws-gg-handson-wc-led-lambda-weather-check"
s3_bucket = "dev-aws-gg-handson-app-resources-<AWS Account ID>"
s3_prefix = "dev/aws-gg-handson/wc-led/lambda/weather-check"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
disable_rollback = false
parameter_overrides = [
  "env=dev",
  "pj=aws-gg-handson",
  "pjc=aws-gg-handson-wc-led",
  "PARTITIONKEY=ThingId",
  "MODELID=anthropic.claude-3-haiku-20240307-v1:0",
  "IOTENDPOINT=xxxxxxxxxxxxx-ats.iot.ap-northeast-1.amazonaws.com",
  "TTSMODEL=Tomoko",
  "REGION=ap-northeast-1",
  "INFERENCEPROFILEARN=arn:aws:bedrock:ap-northeast-1:xxxxxxxxxxxxx:application-inference-profile/xxxxxxxxxxx"
]
tags = [
  "pj=\"aws-gg-handson\"",
  "pjc=\"aws-gg-handson-wc-led\"",
  "user=\"ShiroUz\"",
  "env=\"dev\"",
  "deployment-type=\"SAM\""
]
